[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "."
  functions_timeout = 24


[dev]
  autoLaunch = false
  functions_timeout = 24

[functions]
  node_bundler = "esbuild"
  external_node_modules = []

[[redirects]]
  from = "/.well-known/apple-developer-merchantid-domain-association"
  to = "/.well-known/apple-developer-merchantid-domain-association"
  status = 200
  force = true



[[scheduled.functions]]
  name = "ngteco-sync"
  schedule = "0 0 * * *" # Runs every day at midnight UTC




[[redirects]]
  from = "/api/create-user"
  to = "/.netlify/functions/create-user"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for caching strategies
[[headers]]
  # HTML files (short caching)
  for = "*.html"
  [headers.values]
  Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  # CSS and JavaScript (long caching)
  for = "*.css"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Authorization"


[[headers]]
  for = "*.mjs"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# Images (long caching)
[[headers]]
  for = "*.png"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.gif"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.ico"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# Fonts (long caching)
[[headers]]
  for = "*.woff"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
  Access-Control-Allow-Origin = "*"
    Content-Security-Policy-Report-Only = "default-src 'self'; font-src 'self' https://ticket.funkhaus-berlin.net/;"
  Content-Type = "application/font-woff"
  Server = "YourServerName"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains"
  Vary = "Origin"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"


[[headers]]
  for = "*.woff2"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
  Access-Control-Allow-Origin = "*" 


[[headers]]
  for = "*.ttf"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.otf"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.eot"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# Videos and Audios (long caching)
[[headers]]
  for = "*.mp4"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.mp3"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.wav"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webm"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# Other static files (moderate caching)
[[headers]]
  for = "*.*"
  [headers.values]
  Cache-Control = "public, max-age=86400" # 24 hours

# Note: This configuration aims to cover a wide range of file types. Depending on your specific needs, you might want to adjust the caching duration or add more file types.
